[package]
name = "reformy"
version = "0.1.6"
edition = "2024"
description = "Derive ratatui form widgets from structs or enums"
license = "GPL-3.0-or-later"

[dependencies]
reformy-derive = { path = "../reformy-derive", version = "0.1.6" }
tui-textarea.workspace = true
crossterm.workspace = true
ratatui.workspace = true
