[package]
name = "reformy-core"
version = "0.1.0"
edition = "2024"
description = "helper for 'reformy' crate"
license = "GPL-3.0-or-later"

[dependencies]
tui-textarea.workspace = true
crossterm.workspace = true
ratatui.workspace = true
