[package]
name = "reformy-macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true


[dependencies]
crossterm.workspace = true
ratatui.workspace = true
quote.workspace = true
syn.workspace = true
proc-macro2.workspace = true
tui-textarea.workspace = true
